server:
  tomcat:
    accesslog:
      enabled: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-psql.sql
  spring:
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org:hibernate:dialect:PostgreSQLDialect
    datasource:
      url: ${JDBC_DATABASE_URL}
      username: ${USERNAME}
      password: ${PASSWORD}
  
  logging:
    level:
      root: WARN