spring:
  application:
  name: 1221-systems
  profiles:
    default: dev
  jpa:
    properties:
      hibernate:
        event:
          merge:
            entity_copy_observer: allow
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  output:
    ansi:
      enabled: always

user:
  floatPrecision: 0.01f
  suggestion:
    slim: 0.15f
    main: 1
    gain: 1.15f